joint_names: ["arm_1_joint","arm_2_joint","arm_3_joint","arm_4_joint","arm_5_joint","arm_6_joint","arm_7_joint"]

# single positions
home: [[0,0,0,0,0,0,0]]
folded: [[-1.1572567240035734, -1.9104664691761568, -2.5334780195730255, -1.7853311980377056, -0.072798739390243047, 0.91767934923272776, -1.8876618005378798]]
pregrasp: [[-1.3813422735995828, -1.9312548399287899, -1.7251153715474463, -1.4565057632094409, 0.7169946808744756, 1.0560171841958719, -2.1230019199424044]]
grasp: [[-0.94338446021682099, -1.987128639793466, -1.6757425957025061, -1.2319960038941786, 0.92698961598913809, 0.7957495543301375, -2.2609604309432707]]
overtray: [[2.9057230949401855, -1.0808877189967294, -2.8570542335510254, -1.4864857196807861, 0.57246458530426025, 1.069308876991272, -1.9589838981628416]]
tray: [[2.8545925371816212, -1.1411602564796222, -2.879793265790644, -1.4768269321056455, 0.55049237134044171, 1.0657754724693511, -2.029771517204098]]
intermediateback: [[-0.37676621210148459, -1.1834865325160073, -1.9195156781180045, -1.900762761236517, 0.47636017870775127, 1.4150676891038048, -2.7540395910497537]]
intermediatebacklow: [[0.34600003337848573, -1.6400000103328185, -1.8149999713886731, -1.6349999713897863, -2.9670597283903604, -0.95000002861023169, 1.9699999904632339]]
intermediatefront: [[2.567286997401903, -0.76650447903842134, -2.879793265790644, -1.3169067774275871, 0.59769801545593759, 1.3751587638740583, -1.9299075952888678]]
wavein: [[1.5, 0.5, 0.0, -0.5, 0.0, 0.5, 0.0]]
waveout: [[1.5, 0.5, 0.0, 0.5, 0.0, -0.5, 0.0]]

# trajectories
grasp-to-tray: [pregrasp, intermediateback, intermediatefront, overtray]
tray-to-folded: [intermediatefront, intermediatebacklow, folded]
wave: [waveout, wavein, waveout, wavein]
