joint_names: ["torso_lower_neck_tilt_joint","torso_pan_joint","torso_upper_neck_tilt_joint"]
home: [[0.0,0.0,0.0]]
left: [[0.0,-0.1,0.0]]
right: [[0.0,0.1,0.0]]
front: [[-0.1,0.0,-0.15]]
front_left: [[-0.1,0.1,-0.15]]
front_right: [[-0.1,-0.1,-0.15]]
back: [[0.1,0.0,0.15]]
back_left: [[0.1,0.1,0.15]]
back_right: [[0.1,-0.1,0.15]]
nod: [front,back,front,home]
shake: [left, right, left, home]
lookontray: [[-0.174,0,-0.262]]
bow: [[-0.15,0,-0.3], home]
